spring:
  application:
    name: hanshan-user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanshan
    username: root
    password: 1234qwer
  # session失效时间
  session:
    timeout: 86400
  # 文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
