spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.33.10:3306/hanshan
    username: root
    password: 1234qwer
  # session失效时间
  session:
    timeout: 86400
  # 文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

knife4j:
  enable: off
  openapi:
    title: 与山寒用户中心
    description: 与山寒用户中心接口文档
    email: 1470397437@qq.com
    concat: 寒山
    url: https://github.com/a919001
    version: v4.0
    terms-of-service-url: https://github.com/a919001
    group:
      test1:
        group-name: UserController
        api-rule: package
        api-rule-resources:
          - com.hanshan.hanshanusercenterbackend.controller
