spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.33.10:3306/hanshan
    username: root
    password: 1234qwer
  # session失效时间
  session:
    timeout: 86400
  # 文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
